### ISSUE TITLE
problem with using `viz_recommend` when displaying

### ISSUE THREAD

**Issue by CamilaAchuri** [jpmarindiaz/pseudoviz#4]
Al usar la funcion `pseudoviz::viz_recommend` y desplegar en una aplicación aparece el siguiente error, aun llamando la libreria `ggmagic` en el entorno de la aplicación

<img width="839" alt="image" src="https://github.com/datasketch/pseudoviz/assets/17035597/8b5b89a3-c8f6-4e9c-96ce-0a2d01eee3c6">

Estos mensajes indican que la aplicación está intentando cargar ggmagic, y no esta cargando en el entorno de la aplicacion,  pero me asegure de que el paquete ggmagic esté instalado correctamente, localmente funciona sin problema
Si ggmagic no es un paquete necesario, se puede considerar eliminar o comentar el código que intenta cargarlo.

**Comment by jpmarindiaz** [comment]
Fixed in [d011f56](https://github.com/datasketch/pseudoviz/commit/d011f560b81303b4977af002d86a0d1014c0a830)
